import type {
  CategoryFieldDefinition,
  ItemCategory,
  ItemLibraryIndex,
  ItemLibraryMeta,
} from "../entities/itemLibrarySchema";

export const ITEM_LIBRARY_SCHEMA_VERSION = 1 as const;
export const UNCATEGORIZED_ITEM_CATEGORY_ID = "uncategorized";

const categories: readonly ItemCategory[] = [
  {
    id: UNCATEGORIZED_ITEM_CATEGORY_ID,
    parentId: null,
    name: "未分类",
    description: "尚未归入正式分类的物品。",
    icon: "inbox",
    order: 0,
    system: true,
  },
  {
    id: "weapons",
    parentId: null,
    name: "兵器",
    description: "用于战斗、仪式或身份象征的武器。",
    icon: "swords",
    order: 10,
  },
  {
    id: "polearms",
    parentId: "weapons",
    name: "长兵器",
    description: "具有长柄、强调距离控制的兵器。",
    icon: "move-up-right",
    order: 10,
  },
  {
    id: "spears",
    parentId: "polearms",
    name: "枪",
    description: "以刺击为主的长柄兵器。",
    icon: "move-up-right",
    order: 10,
  },
  {
    id: "short-weapons",
    parentId: "weapons",
    name: "短兵器",
    description: "适合近身使用和随身携带的兵器。",
    icon: "sword",
    order: 20,
  },
  {
    id: "artifacts",
    parentId: null,
    name: "法宝",
    description: "拥有超自然能力、规则或代价的器物。",
    icon: "gem",
    order: 20,
  },
  {
    id: "potions",
    parentId: null,
    name: "药剂",
    description: "可服用、涂抹或投掷使用的消耗品。",
    icon: "flask-conical",
    order: 30,
  },
  {
    id: "key-items",
    parentId: null,
    name: "关键道具",
    description: "推动情节、解锁线索或承载秘密的物品。",
    icon: "key-round",
    order: 40,
  },
  {
    id: "currency",
    parentId: null,
    name: "货币",
    description: "用于交换、计价或体现权力关系的媒介。",
    icon: "coins",
    order: 50,
  },
] as const;

const fields: readonly CategoryFieldDefinition[] = [
  {
    id: "weapon-rank",
    ownerCategoryId: "weapons",
    label: "等阶",
    description: "兵器在世界体系中的品阶或稀有度。",
    group: "兵器属性",
    type: "text",
    required: false,
    defaultValue: "",
    options: [],
    order: 10,
  },
  {
    id: "weapon-owner",
    ownerCategoryId: "weapons",
    label: "持有者",
    description: "当前或主要持有这件兵器的角色。",
    group: "叙事关系",
    type: "entity-reference",
    required: false,
    defaultValue: "",
    options: [],
    entityTypes: ["character"],
    order: 20,
  },
  {
    id: "weapon-condition",
    ownerCategoryId: "weapons",
    label: "完好状况",
    description: "兵器当前的物理或灵性状态。",
    group: "兵器属性",
    type: "single-select",
    required: false,
    defaultValue: "完好",
    options: ["完好", "受损", "封印", "损毁"],
    order: 30,
  },
  {
    id: "polearm-length",
    ownerCategoryId: "polearms",
    label: "长度",
    description: "兵器全长。",
    group: "尺寸",
    type: "number",
    required: false,
    defaultValue: 0,
    options: [],
    unit: "cm",
    order: 40,
  },
  {
    id: "polearm-weight",
    ownerCategoryId: "polearms",
    label: "重量",
    description: "兵器总重量。",
    group: "尺寸",
    type: "number",
    required: false,
    defaultValue: 0,
    options: [],
    unit: "kg",
    order: 50,
  },
  {
    id: "spear-material",
    ownerCategoryId: "spears",
    label: "枪材",
    description: "枪头与枪杆使用的主要材料。",
    group: "枪器细节",
    type: "text",
    required: false,
    defaultValue: "",
    options: [],
    order: 60,
  },
  {
    id: "spear-pattern",
    ownerCategoryId: "spears",
    label: "枪纹",
    description: "枪身纹样、铭文及其意义。",
    group: "枪器细节",
    type: "textarea",
    required: false,
    defaultValue: "",
    options: [],
    order: 70,
  },
  {
    id: "spear-restriction",
    ownerCategoryId: "spears",
    label: "使用限制",
    description: "使用这杆枪所需的条件与代价。",
    group: "枪器细节",
    type: "textarea",
    required: false,
    defaultValue: "",
    options: [],
    order: 80,
  },
] as const;

export function createDefaultItemLibraryMeta(): ItemLibraryMeta {
  return {
    schemaVersion: ITEM_LIBRARY_SCHEMA_VERSION,
    categories: categories.map((category) => ({ ...category })),
    fields: fields.map((field) => ({
      ...field,
      options: [...field.options],
      ...(field.entityTypes ? { entityTypes: [...field.entityTypes] } : {}),
    })),
  };
}

export function createEmptyItemLibraryIndex(): ItemLibraryIndex {
  return { schemaVersion: ITEM_LIBRARY_SCHEMA_VERSION, items: [] };
}
