// Full request translation: Anthropic → OpenAI

import type { AnthropicRequest } from '../types/anthropic';
import type { OpenAIRequest } from '../types/openai';
import type { BridgeConfig } from '../types/bridge';
import { translateMessages } from './messages';
import { translateToolDefinitions, translateToolChoice } from './tools';
import type { ToolImageSaver } from './multimodal';
import { stripModelSuffix } from '../../../shared/contextUsage';


export interface TranslateRequestOptions {
  modelMapping?: BridgeConfig['modelMapping'];
  /** Override model name (highest priority) */
  modelOverride?: string;
  /** Callback to save tool result images to disk (returns relative path) */
  imageSaver?: ToolImageSaver;
  /** #324 — user-selected reasoning effort (NORMALIZED level). Injected as
   *  top-level `reasoning_effort`; absent = field omitted entirely. */
  reasoningEffort?: string;
  /** Stable cache-affinity key generated by the bridge. Never user-authored. */
  promptCacheKey?: string;
  /** Project SDK cache_control markers to target-native content breakpoints. */
  promptCacheBreakpoints?: boolean;
}

/** Translate Anthropic Messages API request → OpenAI Chat Completions request */
export function translateRequest(
  req: AnthropicRequest,
  options?: TranslateRequestOptions,
): OpenAIRequest {
  // 1. Model mapping
  let model = req.model;
  if (options?.modelOverride) {
    model = options.modelOverride;
  } else if (options?.modelMapping) {
    const mapping = options.modelMapping;
    if (typeof mapping === 'function') {
      model = mapping(req.model) ?? req.model;
    } else {
      model = mapping[req.model] ?? req.model;
    }
  }
  // SDK-ingress-only: the `[1m]` / ` 1m` capability decoration MUST NOT reach
  // the upstream wire (#338). `req.model` arrives already-normalized (the SDK
  // strips `[1m]` via normalizeModelStringForAPI), but `modelOverride` /
  // `modelMapping` come straight from config — a stored `claude-X[1m]` or
  // hand-typed `claude-X 1m` would otherwise be forwarded verbatim to the
  // OpenAI-compatible API, which knows only the bare id.
  model = stripModelSuffix(model) ?? model;

  // 2. Messages (system extraction + role mapping + tool_result splitting)
  const thinkingEnabled = req.thinking?.type === 'enabled';
  const messages = translateMessages(
    req.system,
    req.messages,
    thinkingEnabled,
    options?.imageSaver,
    options?.promptCacheBreakpoints === true,
  );

  // 3. Build request
  // NOTE: max_tokens, temperature, top_p, stop are intentionally NOT forwarded.
  // - max_tokens: SDK sends Claude-scale values (128k); the handler injects the user-configured
  //   cap via the correct param name (max_tokens / max_completion_tokens) based on provider config.
  // - temperature, top_p, stop: Anthropic SDK values may not be compatible with the target model
  //   (e.g., reasoning models reject non-default temperature/top_p/stop). Let upstream use defaults.
  const openaiReq: OpenAIRequest = {
    model,
    messages,
  };
  if (options?.promptCacheKey) openaiReq.prompt_cache_key = options.promptCacheKey;

  // 4. Tools
  if (req.tools && req.tools.length > 0) {
    openaiReq.tools = translateToolDefinitions(req.tools);
  }
  if (req.tool_choice) {
    openaiReq.tool_choice = translateToolChoice(req.tool_choice);
    // Map disable_parallel_tool_use → parallel_tool_calls
    if ('disable_parallel_tool_use' in req.tool_choice && req.tool_choice.disable_parallel_tool_use) {
      openaiReq.parallel_tool_calls = false;
    }
  }

  // 5. Stream
  if (req.stream) {
    openaiReq.stream = true;
    openaiReq.stream_options = { include_usage: true };
  }

  // 6. Reasoning effort (#324): forwarded ONLY when the user explicitly
  // selected a non-default effort in the 推理强度 picker. The default omits
  // the field entirely — many OpenAI-compatible providers reject unknown
  // args with 400 "Unrecognized request argument", so unsolicited injection
  // is never safe. The SDK's own `thinking` field is NOT mapped (an
  // Anthropic-side knob with no portable OpenAI equivalent).
  if (options?.reasoningEffort) {
    openaiReq.reasoning_effort = options.reasoningEffort;
  }

  return openaiReq;
}
