// Request translation: Anthropic → OpenAI Responses API

import type { AnthropicRequest, AnthropicMessage, AnthropicToolResultBlock, AnthropicSystemBlock } from '../types/anthropic';
import type { ResponsesRequest, ResponsesInputItem, ResponsesInputContentPart, ResponsesInputFunctionCall, ResponsesToolChoice } from '../types/openai-responses';
import type { BridgeConfig } from '../types/bridge';
import type { ToolImageSaver } from './multimodal';
import { stripModelSuffix } from '../../../shared/contextUsage';
import { projectPromptCacheBreakpoint } from './cache-semantics';


export interface TranslateRequestResponsesOptions {
  modelMapping?: BridgeConfig['modelMapping'];
  modelOverride?: string;
  imageSaver?: ToolImageSaver;
  /** #324 — user-selected reasoning effort (NORMALIZED level). Injected as
   *  `reasoning: { effort }`; absent = field omitted entirely. */
  reasoningEffort?: string;
  /** Stable cache-affinity key generated by the bridge. Never user-authored. */
  promptCacheKey?: string;
  /** Project SDK cache_control markers to target-native content breakpoints. */
  promptCacheBreakpoints?: boolean;
}

/** Translate Anthropic Messages API request → OpenAI Responses API request */
export function translateRequestToResponses(
  req: AnthropicRequest,
  options?: TranslateRequestResponsesOptions,
): ResponsesRequest {
  // 1. Model mapping
  let model = req.model;
  if (options?.modelOverride) {
    model = options.modelOverride;
  } else if (options?.modelMapping) {
    const mapping = options.modelMapping;
    if (typeof mapping === 'function') {
      model = mapping(req.model) ?? req.model;
    } else {
      model = mapping[req.model] ?? req.model;
    }
  }
  // SDK-ingress-only: strip the `[1m]` / ` 1m` capability decoration before the
  // wire (#338) — same rationale as the Chat Completions translator. Config-fed
  // modelOverride / modelMapping can carry a stored suffix the upstream rejects.
  model = stripModelSuffix(model) ?? model;

  const promptCacheBreakpoints = options?.promptCacheBreakpoints === true;

  // 2. Instructions (system prompt)
  let instructions: string | undefined;
  let developerSystemMessage: ResponsesInputItem | undefined;
  if (req.system) {
    if (Array.isArray(req.system) && promptCacheBreakpoints) {
      const systemText = req.system.map(block => block.text).join('\n\n');
      if (systemText) {
        developerSystemMessage = {
          role: 'developer',
          content: req.system.map((block, index) => {
            const breakpoint = projectPromptCacheBreakpoint(true, block.cache_control);
            return {
              type: 'input_text' as const,
              text: `${index > 0 ? '\n\n' : ''}${block.text}`,
              ...(breakpoint ? { prompt_cache_breakpoint: breakpoint } : {}),
            };
          }),
        };
      }
    } else {
      instructions = typeof req.system === 'string'
        ? req.system
        : (req.system as AnthropicSystemBlock[]).map(b => b.text).join('\n\n');
    }
  }

  // 3. Input messages
  const input = translateMessagesToResponses(
    req.messages,
    options?.imageSaver,
    promptCacheBreakpoints,
  );
  if (developerSystemMessage) input.unshift(developerSystemMessage);

  // 4. Build request
  // NOTE: max_output_tokens, temperature, top_p are intentionally NOT forwarded.
  // - max_output_tokens: handler injects user-configured cap via the correct param name.
  // - temperature, top_p: SDK values may not be compatible with target model. Let upstream use defaults.
  const responsesReq: ResponsesRequest = {
    model,
    input,
  };

  if (instructions) responsesReq.instructions = instructions;
  if (options?.promptCacheKey) responsesReq.prompt_cache_key = options.promptCacheKey;

  // 5. Tools
  if (req.tools && req.tools.length > 0) {
    responsesReq.tools = req.tools.map(t => ({
      type: 'function' as const,
      name: t.name,
      description: t.description,
      parameters: t.input_schema,
    }));
  }

  // 6. Tool choice
  if (req.tool_choice) {
    responsesReq.tool_choice = translateToolChoiceToResponses(req.tool_choice);
  }

  // 7. Stream
  if (req.stream) {
    responsesReq.stream = true;
  }

  // 8. Reasoning effort (#324): forwarded ONLY when the user explicitly
  // selected a non-default effort — same omit-by-default rationale as the
  // Chat Completions translator (unknown args → 400 on strict providers).
  if (options?.reasoningEffort) {
    responsesReq.reasoning = { effort: options.reasoningEffort };
  }

  return responsesReq;
}

function translateToolChoiceToResponses(choice: NonNullable<AnthropicRequest['tool_choice']>): ResponsesToolChoice {
  switch (choice.type) {
    case 'auto': return 'auto';
    case 'any': return 'required';
    case 'none': return 'none';
    case 'tool': return { type: 'function', name: choice.name };
  }
}

function translateMessagesToResponses(
  messages: AnthropicMessage[],
  imageSaver?: ToolImageSaver,
  promptCacheBreakpoints = false,
): ResponsesInputItem[] {
  const result: ResponsesInputItem[] = [];

  // Collect known tool_use_ids for orphan detection
  const knownToolUseIds = new Set<string>();
  for (const msg of messages) {
    if (msg.role === 'assistant' && Array.isArray(msg.content)) {
      for (const block of msg.content) {
        if (block.type === 'tool_use') {
          knownToolUseIds.add(block.id);
        }
      }
    }
  }

  for (const msg of messages) {
    if (msg.role === 'user') {
      translateUserMessageToResponses(
        msg,
        result,
        knownToolUseIds,
        imageSaver,
        promptCacheBreakpoints,
      );
    } else if (msg.role === 'assistant') {
      translateAssistantMessageToResponses(msg, result);
    }
  }

  return result;
}

function translateUserMessageToResponses(
  msg: AnthropicMessage,
  result: ResponsesInputItem[],
  knownToolUseIds: Set<string>,
  imageSaver?: ToolImageSaver,
  promptCacheBreakpoints = false,
): void {
  if (typeof msg.content === 'string') {
    result.push({ role: 'user', content: msg.content });
    return;
  }

  const toolResults: AnthropicToolResultBlock[] = [];
  const orphanTexts: string[] = [];
  const otherParts: ResponsesInputContentPart[] = [];

  for (const block of msg.content) {
    if (block.type === 'tool_result') {
      if (knownToolUseIds.has(block.tool_use_id)) {
        toolResults.push(block);
      } else {
        const content = extractToolResultText(block, imageSaver);
        if (content) orphanTexts.push(`[Previous tool result]:\n${content}`);
      }
    } else if (block.type === 'text') {
      const breakpoint = projectPromptCacheBreakpoint(promptCacheBreakpoints, block.cache_control);
      otherParts.push({
        type: 'input_text',
        text: block.text,
        ...(breakpoint ? { prompt_cache_breakpoint: breakpoint } : {}),
      });
    } else if (block.type === 'image') {
      const breakpoint = projectPromptCacheBreakpoint(promptCacheBreakpoints, block.cache_control);
      if (block.source.type === 'url' && block.source.url) {
        otherParts.push({
          type: 'input_image',
          image_url: block.source.url,
          ...(breakpoint ? { prompt_cache_breakpoint: breakpoint } : {}),
        });
      } else if (block.source.data) {
        const mediaType = block.source.media_type || 'image/png';
        otherParts.push({
          type: 'input_image',
          image_url: `data:${mediaType};base64,${block.source.data}`,
          ...(breakpoint ? { prompt_cache_breakpoint: breakpoint } : {}),
        });
      }
    }
    // thinking blocks filtered
  }

  // Emit function_call_output items for tool results
  for (const tr of toolResults) {
    result.push({
      type: 'function_call_output',
      call_id: tr.tool_use_id,
      output: extractToolResultText(tr, imageSaver),
    });
  }

  // Add orphan text to other parts
  for (const text of orphanTexts) {
    otherParts.push({ type: 'input_text', text });
  }

  // Emit user message for remaining content
  if (otherParts.length > 0) {
    if (otherParts.length === 1
        && otherParts[0].type === 'input_text'
        && !otherParts[0].prompt_cache_breakpoint) {
      result.push({ role: 'user', content: otherParts[0].text });
    } else {
      result.push({ role: 'user', content: otherParts });
    }
  }
}

function translateAssistantMessageToResponses(msg: AnthropicMessage, result: ResponsesInputItem[]): void {
  if (typeof msg.content === 'string') {
    result.push({ role: 'assistant', content: msg.content });
    return;
  }

  // Build assistant content parts and function calls
  const contentParts: ResponsesInputContentPart[] = [];
  const functionCalls: ResponsesInputFunctionCall[] = [];

  for (const block of msg.content) {
    if (block.type === 'text') {
      contentParts.push({ type: 'output_text', text: block.text });
    } else if (block.type === 'tool_use') {
      // In Responses API input replay, function calls are separate items
      functionCalls.push({
        type: 'function_call',
        call_id: block.id,
        name: block.name,
        arguments: typeof block.input === 'string' ? block.input : JSON.stringify(block.input),
      });
    }
    // thinking blocks are not replayed in input
  }

  // Emit text content as assistant message
  if (contentParts.length > 0) {
    result.push({ role: 'assistant', content: contentParts });
  }

  // Emit each function call as a separate input item
  for (const fc of functionCalls) {
    result.push(fc);
  }

  // If no content and no function calls, emit empty assistant message
  if (contentParts.length === 0 && functionCalls.length === 0) {
    result.push({ role: 'assistant', content: '' });
  }
}

function extractToolResultText(tr: AnthropicToolResultBlock, imageSaver?: ToolImageSaver): string {
  const isError = tr.is_error === true;
  if (!tr.content) return isError ? '<error></error>' : '';

  let text: string;
  if (typeof tr.content === 'string') {
    text = tr.content;
  } else {
    const parts: string[] = [];
    for (const c of tr.content) {
      if (c.type === 'text') {
        parts.push(c.text);
      } else if (c.type === 'image') {
        if (imageSaver && c.source?.data) {
          try {
            const relPath = imageSaver(c.source.data, c.source.media_type || 'image/png');
            parts.push(`[Tool returned an image, saved to ${relPath}]`);
          } catch {
            parts.push('[Tool returned an image, failed to save]');
          }
        } else {
          parts.push('[Image content omitted - tool returned an image]');
        }
      }
    }
    text = parts.join('\n');
  }

  return isError ? `<error>${text}</error>` : text;
}
