import type {
  SettingLibraryMeta,
  SettingLibrarySettingsIndex,
  SettingLibrarySpatialTree,
  SettingTemplate,
} from "./settingLibrarySchema";

export const SETTING_LIBRARY_SCHEMA_VERSION = 1 as const;

const templates: readonly SettingTemplate[] = [
  {
    id: "universe-overview",
    name: "宇宙总览",
    group: "世界",
    description: "概括宇宙的叙事定位、边界与核心特征。",
    source: "builtin",
    version: "1.3.0",
    skeleton:
      "# 宇宙总览\n\n> 用一句话定义这个宇宙在故事中的独特位置。\n\n## 核心特征\n\n- \n\n## 空间边界\n\n## 叙事用途\n",
    agentGuide:
      "帮助作者区分设定事实与叙事功能；发现空泛描述时追问可被角色观察到的证据。",
  },
  {
    id: "universe-structure",
    name: "宇宙结构",
    group: "世界",
    description: "描述宇宙的主要区域、尺度和边界。",
    source: "builtin",
    version: "1.1.0",
    skeleton: "# 宇宙结构\n\n## 空间分区\n\n## 边界与通道\n\n## 观测限制\n",
    agentGuide: "优先梳理空间结构，不自动创建下级节点。",
  },
  {
    id: "spacetime-rules",
    name: "时空规则",
    group: "世界",
    description: "记录时间、距离与跨域移动的基本规则。",
    source: "builtin",
    version: "1.2.0",
    skeleton:
      "# 时空规则\n\n## 时间流速\n\n## 空间距离\n\n## 穿越条件\n\n## 已知例外\n",
    agentGuide: "检查规则是否可被剧情利用，并提醒作者记录例外的代价。",
  },
  {
    id: "basic-laws",
    name: "基础法则",
    group: "世界",
    description: "定义物理、魔法或超自然现象的底层约束。",
    source: "builtin",
    version: "1.4.0",
    skeleton:
      "# 基础法则\n\n## 可观测法则\n\n## 能量来源\n\n## 不可突破的边界\n",
    agentGuide: "避免替作者补全体系，只基于已给事实检查自洽性。",
  },
  {
    id: "civilization-distribution",
    name: "文明分布",
    group: "社会",
    description: "记录主要文明在当前空间尺度的分布。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 文明分布\n\n## 已知文明\n\n## 未探索区域\n\n## 交流条件\n",
    agentGuide: "提示作者将重要文明建立为对应空间节点或词条。",
  },
  {
    id: "macro-factions",
    name: "宏观势力",
    group: "政治",
    description: "梳理能跨越多个下级空间活动的主要势力。",
    source: "builtin",
    version: "1.2.0",
    skeleton: "# 宏观势力\n\n## 势力概览\n\n## 活动区域\n\n## 彼此关系\n",
    agentGuide: "聚焦势力在当前节点中的事实，关系图谱由索引层派生。",
  },
  {
    id: "cosmic-events",
    name: "宇宙级重大事件",
    group: "历史",
    description: "记录改变当前空间状态的关键历史事件。",
    source: "builtin",
    version: "1.1.0",
    skeleton:
      "# 宇宙级重大事件\n\n## 事件时间线\n\n## 直接影响\n\n## 长期余波\n",
    agentGuide: "使用明确前因、转折与可见后果记录事件。",
  },
  {
    id: "country-overview",
    name: "国家总览",
    group: "政治",
    description: "概括国家或主权城市的定位、政体与叙事作用。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 国家总览\n\n## 一句话定位\n\n## 政体概览\n\n## 核心矛盾\n",
    agentGuide: "优先确认该政治实体在故事当下的真实状态。",
  },
  {
    id: "territory",
    name: "疆域",
    group: "地理",
    description: "记录疆界、地形和内部空间分区。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 疆域\n\n## 边界\n\n## 主要区域\n\n## 交通节点\n",
    agentGuide: "提醒作者把可独立编辑的重要地点加入空间树。",
  },
  {
    id: "politics",
    name: "政治",
    group: "政治",
    description: "记录权力结构和决策机制。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 政治\n\n## 权力结构\n\n## 决策机制\n\n## 当前矛盾\n",
    agentGuide: "区分正式制度与实际权力。",
  },
  {
    id: "military",
    name: "军事",
    group: "军事",
    description: "记录军制、力量和战略能力。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 军事\n\n## 军制\n\n## 主要力量\n\n## 战略限制\n",
    agentGuide: "避免虚构精确数字，未知规模使用待核定标记。",
  },
  {
    id: "economy",
    name: "经济",
    group: "经济",
    description: "记录资源、生产与交换网络。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 经济\n\n## 核心资源\n\n## 生产体系\n\n## 贸易与货币\n",
    agentGuide: "追问资源如何影响普通人的选择。",
  },
  {
    id: "law",
    name: "法律",
    group: "政治",
    description: "记录法律来源、执行和重要禁令。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 法律\n\n## 法律来源\n\n## 执行机构\n\n## 重要法律\n",
    agentGuide: "区分成文规则与实际执行。",
  },
  {
    id: "society",
    name: "社会",
    group: "社会",
    description: "记录阶层、组织与社会流动。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 社会\n\n## 社会结构\n\n## 阶层流动\n\n## 公共议题\n",
    agentGuide: "从角色日常经验校验宏观描述。",
  },
  {
    id: "culture",
    name: "文化",
    group: "文化",
    description: "记录共同记忆、审美与习俗。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 文化\n\n## 共同记忆\n\n## 节庆与习俗\n\n## 审美偏好\n",
    agentGuide: "鼓励具体器物、动作和场景，而不是抽象形容。",
  },
  {
    id: "religion",
    name: "宗教",
    group: "文化",
    description: "记录信仰体系与宗教实践。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 宗教\n\n## 信仰对象\n\n## 组织与仪式\n\n## 世俗影响\n",
    agentGuide: "区分信仰事实、教义主张和角色认知。",
  },
  {
    id: "ethnicity",
    name: "民族",
    group: "社会",
    description: "记录群体身份、迁徙与共存关系。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 民族\n\n## 群体构成\n\n## 历史迁徙\n\n## 当代关系\n",
    agentGuide: "避免把群体写成单一性格。",
  },
  {
    id: "language",
    name: "语言",
    group: "文化",
    description: "记录语言分布、文字和交流障碍。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 语言\n\n## 语言分布\n\n## 文字系统\n\n## 交流场景\n",
    agentGuide: "提示作者记录称谓和翻译约定。",
  },
  {
    id: "daily-life",
    name: "日常生活",
    group: "社会",
    description: "记录衣食住行与普通人的生活节奏。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 日常生活\n\n## 衣食住行\n\n## 工作与休息\n\n## 普通人的一天\n",
    agentGuide: "用角色可接触的细节检验世界设定。",
  },
  {
    id: "space-overview",
    name: "空间总览",
    group: "世界",
    description: "概括该空间在故事中的定位、尺度与叙事作用。",
    source: "builtin",
    version: "1.0.0",
    skeleton:
      "# 空间总览\n\n> 用一句话说明这个空间在故事中的位置。\n\n## 核心特征\n\n## 边界与通道\n\n## 叙事用途\n",
    agentGuide:
      "区分设定事实与叙事功能；提醒作者把可独立编辑的重要地点加入空间树。",
  },
  {
    id: "cultivation-system",
    name: "修炼体系",
    group: "世界",
    description: "记录该世界的修炼体系、境界与力量来源。",
    source: "builtin",
    version: "1.0.0",
    skeleton:
      "# 修炼体系\n\n## 力量来源\n\n## 境界划分\n\n## 突破条件与代价\n\n## 与本页空间的关系\n",
    agentGuide:
      "结构化数据请在修行体系模块（world/cultivation/index.json 及其体系目录）维护，本页只写叙事层面的说明、例外与作者确认的设定。",
  },
  {
    id: "sect",
    name: "宗门",
    group: "政治",
    description: "记录宗门、家族、学府等组织的定位与内部结构。",
    source: "builtin",
    version: "1.0.0",
    skeleton:
      "# 宗门\n\n## 一句话定位\n\n## 组织架构\n\n## 传承与功法\n\n## 对外关系\n",
    agentGuide:
      "结构化势力资料请在势力模块维护，本页只保存本空间内的叙事事实与组织概述。",
  },
  {
    id: "spiritual-veins",
    name: "灵脉秘境",
    group: "地理",
    description: "记录灵脉、秘境与特殊地利的分布和规则。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 灵脉秘境\n\n## 灵脉分布\n\n## 秘境规则\n\n## 资源与风险\n",
    agentGuide: "与时空规则页保持一致，避免规则自相矛盾。",
  },
  {
    id: "treasures-and-pills",
    name: "异宝丹药",
    group: "经济",
    description: "记录丹药、法宝与天材地宝的类别和流通规则。",
    source: "builtin",
    version: "1.0.0",
    skeleton: "# 异宝丹药\n\n## 类别概览\n\n## 珍稀度与产出\n\n## 流通与代价\n",
    agentGuide: "具体物品资料请在物品库维护，本页写分类与流通规则。",
  },
] as const;

export function createDefaultSettingLibraryMeta(): SettingLibraryMeta {
  return {
    schemaVersion: SETTING_LIBRARY_SCHEMA_VERSION,
    levelTypes: [
      {
        id: "world-root",
        name: "世界根",
        description: "项目中全部世界空间的总入口。",
        icon: "globe-2",
        mapKind: "hidden",
        source: "builtin",
        suggestedParentTypeIds: [],
        suggestedChildTypeIds: ["multiverse", "universe", "planet"],
      },
      {
        id: "multiverse",
        name: "多元宇宙",
        description: "容纳多个宇宙或相互隔离世界体系的空间层级。",
        icon: "sparkles",
        mapKind: "cosmic-region",
        source: "builtin",
        suggestedParentTypeIds: ["world-root"],
        suggestedChildTypeIds: ["universe"],
      },
      {
        id: "universe",
        name: "宇宙",
        description: "拥有共同基础法则和时空结构的完整宇宙。",
        icon: "orbit",
        mapKind: "cosmic-region",
        source: "builtin",
        suggestedParentTypeIds: ["world-root", "multiverse"],
        suggestedChildTypeIds: ["galaxy-group", "star-system", "planet"],
      },
      {
        id: "galaxy-group",
        name: "星系群",
        description: "由多个星系或恒星系构成的大尺度天体集合。",
        icon: "sparkles",
        mapKind: "stellar-region",
        source: "builtin",
        suggestedParentTypeIds: ["universe"],
        suggestedChildTypeIds: ["star-system"],
      },
      {
        id: "star-system",
        name: "恒星系",
        description: "围绕一个或多个恒星组织的天体系统。",
        icon: "sun",
        mapKind: "stellar-region",
        source: "builtin",
        suggestedParentTypeIds: ["universe", "galaxy-group"],
        suggestedChildTypeIds: ["planet"],
      },
      {
        id: "planet",
        name: "星球",
        description: "可承载大陆、文明与独立生态的行星空间。",
        icon: "circle-dot",
        mapKind: "planet-point",
        source: "builtin",
        suggestedParentTypeIds: ["star-system", "universe"],
        suggestedChildTypeIds: ["continent", "country", "independent-city"],
      },
      {
        id: "continent",
        name: "大陆",
        description: "星球上的大型连续陆地或同尺度区域。",
        icon: "land-plot",
        mapKind: "geographic-area",
        source: "builtin",
        suggestedParentTypeIds: ["planet"],
        suggestedChildTypeIds: ["country", "independent-city"],
      },
      {
        id: "country",
        name: "国家",
        description: "具有稳定疆域、组织体系和共同政治身份的国家。",
        icon: "flag",
        mapKind: "geographic-area",
        source: "builtin",
        suggestedParentTypeIds: ["continent", "planet"],
        suggestedChildTypeIds: ["province", "city"],
      },
      {
        id: "province",
        name: "行省",
        description: "国家下辖的区域性行政层级。",
        icon: "map",
        mapKind: "geographic-area",
        source: "builtin",
        suggestedParentTypeIds: ["country"],
        suggestedChildTypeIds: ["city"],
      },
      {
        id: "city",
        name: "城市",
        description: "依附于上级空间的城市或聚落。",
        icon: "building-2",
        mapKind: "settlement-point",
        source: "builtin",
        suggestedParentTypeIds: ["country", "province", "continent"],
        suggestedChildTypeIds: [],
      },
      {
        id: "independent-city",
        name: "独立城市",
        description: "直接归属于大陆、星球或自定义区域的主权城市。",
        icon: "landmark",
        mapKind: "settlement-point",
        source: "builtin",
        suggestedParentTypeIds: ["continent", "planet"],
        suggestedChildTypeIds: [],
      },
      {
        id: "custom-region",
        name: "自定义地域",
        description: "用于作者自定义的非标准空间层级。",
        icon: "brackets",
        mapKind: "geographic-area",
        source: "builtin",
        suggestedParentTypeIds: [],
        suggestedChildTypeIds: [],
      },
    ],
    settingTemplates: templates.map((template) => ({ ...template })),
    profiles: [
      { levelTypeId: "world-root", templateIds: ["universe-overview"] },
      {
        levelTypeId: "multiverse",
        templateIds: [
          "universe-overview",
          "universe-structure",
          "spacetime-rules",
        ],
      },
      {
        levelTypeId: "universe",
        templateIds: [
          "universe-overview",
          "universe-structure",
          "spacetime-rules",
          "basic-laws",
          "civilization-distribution",
          "macro-factions",
          "cosmic-events",
        ],
      },
      {
        levelTypeId: "galaxy-group",
        templateIds: [
          "universe-overview",
          "universe-structure",
          "civilization-distribution",
        ],
      },
      {
        levelTypeId: "star-system",
        templateIds: ["universe-overview", "universe-structure", "basic-laws"],
      },
      {
        levelTypeId: "planet",
        templateIds: [
          "space-overview",
          "territory",
          "civilization-distribution",
          "basic-laws",
          "cultivation-system",
          "spiritual-veins",
        ],
      },
      {
        levelTypeId: "continent",
        templateIds: [
          "space-overview",
          "territory",
          "civilization-distribution",
          "macro-factions",
          "sect",
          "treasures-and-pills",
        ],
      },
      {
        levelTypeId: "country",
        templateIds: [
          "country-overview",
          "territory",
          "politics",
          "military",
          "economy",
          "law",
          "society",
          "culture",
          "religion",
          "ethnicity",
          "language",
          "daily-life",
        ],
      },
      {
        levelTypeId: "province",
        templateIds: [
          "territory",
          "politics",
          "economy",
          "society",
          "culture",
          "daily-life",
        ],
      },
      {
        levelTypeId: "city",
        templateIds: [
          "territory",
          "politics",
          "economy",
          "society",
          "culture",
          "daily-life",
        ],
      },
      {
        levelTypeId: "independent-city",
        templateIds: [
          "country-overview",
          "territory",
          "politics",
          "economy",
          "law",
          "society",
          "culture",
          "daily-life",
        ],
      },
      { levelTypeId: "custom-region", templateIds: ["space-overview"] },
    ],
  };
}

export function createDefaultSettingLibraryTree(
  projectTitle: string,
): SettingLibrarySpatialTree {
  const title = projectTitle.trim() || "未命名小说";
  return {
    schemaVersion: SETTING_LIBRARY_SCHEMA_VERSION,
    nodes: [
      {
        id: "world-root",
        parentId: null,
        name: `${title}世界根`,
        typeId: "world-root",
        order: 0,
      },
    ],
  };
}

export function createEmptySettingLibraryIndex(): SettingLibrarySettingsIndex {
  return { schemaVersion: SETTING_LIBRARY_SCHEMA_VERSION, settings: [] };
}
